name: imports2
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: vaibhavsingh97 <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.3+17

dev_dependencies:
  test: ^1.0.0
